services:
  tg_transmission_bot:
      image: python:3.12.7-bookworm
      container_name: tg_transmission_bot
      restart: always
      working_dir: /bot
      volumes:
        - ./:/bot
      env_file:
        - .env
      command: bash -c "
        pip install -r requirements.txt ;
        python -u bot.py"

